# Change these first
owner: shejulshubham # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: ZeroMOQ
    url: https://www.zeromoq.com/
    method: GET
  - name: Emprog
    url: https://emprog.netlify.app/
    method: GET

status-website:
  name: Website Uptime Monitoring
  introTitle: "This is a real-time status page for ZeroMOQ"
  navbar:
    - title: Status
      href: /
    - title: ZeroMOQ Source Code
      href: https://github.com/TrustAdditive/TrustAdditiveDjango
assignees:
  - shejulshubham

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
